---
# task mod_gearman

- name: disable selinux
  selinux:
    state: disabled

- name: install the 'mod_gearman_worker' repos
  yum:
    name: "{{ mod_gearman_packages }}"
    state: latest

- name: install the 'mod_gearman_worker' packages
  yum:
    name: ['nagios-plugins-all','nagios-plugins-eon','perl-Nagios-Plugin','perl-Net-SNMP']
    state: latest

- name: install 'mod_gearman' packages
  yum:
    name:  ['gearmand', 'gearmand-server', 'mod_gearman']
    state: latest


- name: disable gearmand-server on worker
  service:
    name: gearmand
    enabled: no
    state: stopped

- name: copy secret file to each nodes
  template:
    src: mod_gearman/secret.file.j2
    dest: "{{ mod_gearman_key_path }}"
    owner: root
    group: root
    mode: 0644


- name: generate template worker to worker node
  template:
    src: mod_gearman/worker.conf.j2
    dest: /etc/mod_gearman/worker.conf
    owner: root
    group: root
    mode: 0644

- name: create eyesofnetwork group on worker
  group:
    name: eyesofnetwork
    state: present

- name: add user nagios to eyesofnetwork group on worker
  user:
    name: nagios
    groups: eyesofnetwork

- name: change user context execution for worker
  ini_file:
    path: "/usr/lib/systemd/system/mod-gearman-worker.service"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - { section: "Service", option: "User", value: "nagios" }
    - { section: "Service", option: "Group", value: "eyesofnetwork" }
  notify: reload systemd daemon

- name: Systemd reload now
  meta: flush_handlers

- name: change permission for worker on directory
  file:
    owner: "nagios"
    path: "{{ item }}"
    recurse: yes
  loop:
    - /var/mod_gearman
    - /var/log/mod_gearman

- name: restart mod-gearman-worker on each nodes
  service:
    name: mod-gearman-worker
    enabled: yes
    state: restarted


